server:
  port: 5051
spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database-1.cmpfv9o6r3hf.ap-northeast-2.rds.amazonaws.com:5432/postgres?currentSchema=myworkspace
    username: postgres
    password: password123!
  jpa:
    show-sql: true
    generate-ddl: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq: 
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2
#    addresses: amqps://b-9b495715-2765-4d51-b6c3-ab064d23337a.mq.ap-northeast-2.amazonaws.com:5671
    host: ec2-13-125-158-16.ap-northeast-2.compute.amazonaws.com
    username: rabbitmq
    password: password123
